(function(){'use strict';
var f,h="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},l="object"===typeof h.global&&h.global?h.global:"object"===typeof global&&global&&global.Object===Object?global:this;h.global=l;var aa="object"===typeof h.exportsNamespace&&h.exportsNamespace?h.exportsNamespace:l;h.exportsNamespace=aa;l.Object.freeze(h);var ba={envInfo:h,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.21",globalThis:this};l.Object.freeze(ba);
l.Object.freeze(ba.semantics);var n=l.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=l.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=l.WeakMap?new l.WeakMap:null;function p(a){return function(b,c){return!(!b||!b.$classData||b.$classData.Z!==c||b.$classData.X!==a)}}
function fa(a){for(var b in a)return b}function q(a,b){return ga(a,b,0)}function ga(a,b,c){var d=new a.$a(b[c]);if(c<b.length-1){a=a.ba;c+=1;for(var g=d.a,k=0;k<g.length;k++)g[k]=ga(a,b,c)}return d}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return r(ja);case "number":var b=a|0;return b===a?ka(b)?r(la):ma(b)?r(na):r(oa):"number"===typeof a?r(pa):r(qa);case "boolean":return r(ra);case "undefined":return r(sa);default:return null===a?a.kd():ta(a)?r(ua):a&&a.$classData?r(a.$classData):null}}
function va(a){switch(typeof a){case "string":return wa(xa(),a);case "number":return ya(za(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.B():null===ea?42:Aa(a)}}function Ba(a,b){var c=l.Object.getPrototypeOf,d=l.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function Ca(a,b,c){a=Ba(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Da(a,b,c,d){a=Ba(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new l.TypeError("super has no setter '"+c+"'.");}
var Aa=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return va(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(l.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:va(a)};function ka(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ma(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function u(){this.ya=this.$a=void 0;this.X=this.ba=this.u=null;this.Z=0;this.Ta=null;this.pa="";this.s=this.ma=this.na=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new u;d.u={};d.ba=null;d.Ta=a;d.pa=b;d.s=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function w(a,b,c,d,g,k,e){var t=new u,m=fa(a);k=k||function(a){return!!(a&&a.$classData&&a.$classData.u[m])};e=e||function(a,b){return!!(a&&a.$classData&&a.$classData.Z===b&&a.$classData.X.u[m])};t.ya=g;t.u=c;t.pa="L"+b+";";t.s=e;t.name=b;t.isInterface=!1;t.isRawJSType=!!d;t.isInstance=k;return t}
function Ea(a){function b(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=g}else this.a=a}var c=new u,d=a.Ta,g="longZero"==d?x().la:d;b.prototype=new y;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.pa,k=a.X||a,e=a.Z+1;c.$a=b;c.ya=z;c.u={c:1,Wb:1,f:1};c.ba=a;c.X=k;c.Z=e;c.Ta=null;c.pa=d;c.na=void 0;c.ma=void 0;c.s=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.s(a,e)};return c}
function r(a){if(!a.na){var b=new A;b.qa=a;a.na=b}return a.na}function B(a){a.ma||(a.ma=Ea(a));return a.ma}u.prototype.getFakeInstance=function(){return this===ja?"some string":this===ra?!1:this===la||this===na||this===oa||this===pa||this===qa?0:this===ua?x().la:this===sa?void 0:{$classData:this}};u.prototype.getSuperclass=function(){return this.ya?r(this.ya):null};u.prototype.getComponentType=function(){return this.ba?r(this.ba):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=B(b);return q(b,a)};var Fa=v(!1,"Z","boolean"),Ga=v(0,"C","char"),Ha=v(0,"B","byte"),Ia=v(0,"S","short"),Ja=v(0,"I","int"),Ka=v("longZero","J","long"),La=v(0,"F","float"),Ma=v(0,"D","double");Fa.s=p(Fa);Ga.s=p(Ga);Ha.s=p(Ha);Ia.s=p(Ia);Ja.s=p(Ja);Ka.s=p(Ka);La.s=p(La);Ma.s=p(Ma);function C(){}function y(){}y.prototype=C.prototype;C.prototype.b=function(){return this};C.prototype.r=function(){var a=D(ia(this)),b=(+(this.B()>>>0)).toString(16);return a+"@"+b};C.prototype.B=function(){return Aa(this)};C.prototype.toString=function(){return this.r()};var z=w({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.Z||0;return!(c<b)&&(c>b||!a.X.isPrimitive)}return!1});C.prototype.$classData=z;
function E(a){var b=q(B(z),[a.a.length]),c=a.a.length;a=a.a;var d=b.a;if(a!==d||0>(0+c|0))for(var g=0;g<c;g=g+1|0)d[0+g|0]=a[0+g|0];else for(g=c-1|0;0<=g;g=g-1|0)d[0+g|0]=a[0+g|0];return b}
function Na(a,b,c){if(32>c)return a.j().a[31&b];if(1024>c)return a.d().a[31&(b>>>5|0)].a[31&b];if(32768>c)return a.e().a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(1048576>c)return a.g().a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(33554432>c)return a.l().a[31&(b>>>20|0)].a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(1073741824>c)return a.w().a[31&(b>>>25|0)].a[31&(b>>>20|0)].a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];throw(new F).b();}
function Oa(a,b,c){if(32<=c)if(1024>c)a.i(a.d().a[31&(b>>>5|0)]);else if(32768>c)a.h(a.e().a[31&(b>>>10|0)]),a.i(a.d().a[31&(b>>>5|0)]);else if(1048576>c)a.k(a.g().a[31&(b>>>15|0)]),a.h(a.e().a[31&(b>>>10|0)]),a.i(a.d().a[31&(b>>>5|0)]);else if(33554432>c)a.m(a.l().a[31&(b>>>20|0)]),a.k(a.g().a[31&(b>>>15|0)]),a.h(a.e().a[31&(b>>>10|0)]),a.i(a.d().a[31&(b>>>5|0)]);else if(1073741824>c)a.v(a.w().a[31&(b>>>25|0)]),a.m(a.l().a[31&(b>>>20|0)]),a.k(a.g().a[31&(b>>>15|0)]),a.h(a.e().a[31&(b>>>10|0)]),a.i(a.d().a[31&
(b>>>5|0)]);else throw(new F).b();}function Pa(a,b,c){a.A(c);c=-1+c|0;switch(c){case -1:break;case 0:a.i(b.j());break;case 1:a.h(b.d());a.i(b.j());break;case 2:a.k(b.e());a.h(b.d());a.i(b.j());break;case 3:a.m(b.g());a.k(b.e());a.h(b.d());a.i(b.j());break;case 4:a.v(b.l());a.m(b.g());a.k(b.e());a.h(b.d());a.i(b.j());break;case 5:a.ea(b.w());a.v(b.l());a.m(b.g());a.k(b.e());a.h(b.d());a.i(b.j());break;default:throw(new G).va(c);}}function Qa(){this.Ya=this.Wa=0}Qa.prototype=new y;
Qa.prototype.constructor=Qa;Qa.prototype.b=function(){this.Wa=8.1E-6;this.Ya=1.83E-4;return this};Qa.prototype.$classData=w({Mb:0},"Analyzer$",{Mb:1,c:1});var Ra=void 0;function H(){}H.prototype=new y;H.prototype.constructor=H;H.prototype.b=function(){return this};
H.prototype.analyze=function(a,b,c){a=+a;b=+b;c=+c;Ra||(Ra=(new Qa).b());var d=Ra,g=a+b;Sa||(Sa=(new I).b());Ta();Sa||(Sa=(new I).b());Ua();a=(new Va).b();for(var k=100;;){var e=b+b*k/1E3,t=new Wa,m=+l.Math.abs(e-(b+g*(1+d.Ya*(e-c)/(1+3*d.Wa*(e-c))))+g);t.G=e;t.ra=m;e=a;if(e.K>=e.da.a.length){var m=32+e.$|0,L=e.$^m;if(1024>L)1===e.o()&&(e.h(q(B(z),[32])),e.d().a[0]=e.j(),e.A(1+e.o()|0)),e.i(q(B(z),[32])),e.d().a[31&(m>>>5|0)]=e.j();else if(32768>L)2===e.o()&&(e.k(q(B(z),[32])),e.e().a[0]=e.d(),e.A(1+
e.o()|0)),e.i(q(B(z),[32])),e.h(q(B(z),[32])),e.d().a[31&(m>>>5|0)]=e.j(),e.e().a[31&(m>>>10|0)]=e.d();else if(1048576>L)3===e.o()&&(e.m(q(B(z),[32])),e.g().a[0]=e.e(),e.A(1+e.o()|0)),e.i(q(B(z),[32])),e.h(q(B(z),[32])),e.k(q(B(z),[32])),e.d().a[31&(m>>>5|0)]=e.j(),e.e().a[31&(m>>>10|0)]=e.d(),e.g().a[31&(m>>>15|0)]=e.e();else if(33554432>L)4===e.o()&&(e.v(q(B(z),[32])),e.l().a[0]=e.g(),e.A(1+e.o()|0)),e.i(q(B(z),[32])),e.h(q(B(z),[32])),e.k(q(B(z),[32])),e.m(q(B(z),[32])),e.d().a[31&(m>>>5|0)]=e.j(),
e.e().a[31&(m>>>10|0)]=e.d(),e.g().a[31&(m>>>15|0)]=e.e(),e.l().a[31&(m>>>20|0)]=e.g();else if(1073741824>L)5===e.o()&&(e.ea(q(B(z),[32])),e.w().a[0]=e.l(),e.A(1+e.o()|0)),e.i(q(B(z),[32])),e.h(q(B(z),[32])),e.k(q(B(z),[32])),e.m(q(B(z),[32])),e.v(q(B(z),[32])),e.d().a[31&(m>>>5|0)]=e.j(),e.e().a[31&(m>>>10|0)]=e.d(),e.g().a[31&(m>>>15|0)]=e.e(),e.l().a[31&(m>>>20|0)]=e.g(),e.w().a[31&(m>>>25|0)]=e.l();else throw(new F).b();e.$=m;e.K=0}e.da.a[e.K]=t;e.K=1+e.K|0;if(0===k)break;k=-1+k|0}b=a.$+a.K|0;
0===b?d=Ua().Va:(c=(new Xa).Ja(0,b,0),Pa(c,a,a.ca),1<a.ca&&Oa(c,0,-1+b|0),d=c);Ya||(Ya=(new Za).b());if(0===d.yb(0))throw(new $a).D("empty.minBy");a=b=null;c=!0;for(d=ab(d);d.V;)if(g=d.L(),k=g.ra,c||k<+b)a=g,b=k,c=!1;return a.G};H.prototype.$classData=w({Ob:0},"Main$",{Ob:1,c:1});var bb=void 0;function A(){this.qa=null}A.prototype=new y;A.prototype.constructor=A;function D(a){return a.qa.name}A.prototype.r=function(){return(this.qa.isInterface?"interface ":this.qa.isPrimitive?"":"class ")+D(this)};
A.prototype.$classData=w({Vb:0},"java.lang.Class",{Vb:1,c:1});function J(){}J.prototype=new y;J.prototype.constructor=J;function cb(){}cb.prototype=J.prototype;J.prototype.Ka=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};J.prototype.T=function(a,b){a=this.Ka(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};J.prototype.fa=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};
function db(a,b,c){var d=(new K).ga(0);c=(new K).ga(c);b.ua(eb(function(a,b,c){return function(d){c.p=a.T(c.p,fb(M(),d));b.p=1+b.p|0}}(a,d,c)));return a.fa(c.p,d.p)}function gb(){this.rb=null}gb.prototype=new y;gb.prototype.constructor=gb;gb.prototype.b=function(){hb=this;this.rb=(new N).b();return this};gb.prototype.$classData=w({Dc:0},"scala.collection.Iterator$",{Dc:1,c:1});var hb=void 0;function ib(a,b,c){return a.Xa((new O).b(),b,c,")").y.q}
function jb(a,b,c,d,g){var k=kb();lb(b,c);a.ua(eb(function(a,b,c,d){return function(a){if(d.p)mb(b,a),d.p=!1;else return lb(b,c),mb(b,a)}}(a,b,d,k)));lb(b,g);return b}function nb(){}nb.prototype=new y;nb.prototype.constructor=nb;function ob(){}ob.prototype=nb.prototype;function pb(){this.N=!1;this.ub=this.xa=this.Y=null;this.Aa=!1;this.zb=this.vb=0}pb.prototype=new y;pb.prototype.constructor=pb;
pb.prototype.b=function(){qb=this;this.Y=(this.N=!!(l.ArrayBuffer&&l.Int32Array&&l.Float32Array&&l.Float64Array))?new l.ArrayBuffer(8):null;this.xa=this.N?new l.Int32Array(this.Y,0,2):null;this.N&&new l.Float32Array(this.Y,0,2);this.ub=this.N?new l.Float64Array(this.Y,0,1):null;if(this.N)this.xa[0]=16909060,a=1===((new l.Int8Array(this.Y,0,8))[0]|0);else var a=!0;this.vb=(this.Aa=a)?0:1;this.zb=this.Aa?1:0;return this};
function ya(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.N)a.ub[0]=b,a=(new P).C(a.xa[a.zb]|0,a.xa[a.vb]|0);else{if(b!==b)a=!1,b=2047,c=+l.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+l.Math.pow(2,-1022)){b=+l.Math.pow(2,52);var c=+l.Math.log(d)/.6931471805599453,c=+l.Math.floor(c)|0,c=1023>c?c:1023,g=+l.Math.pow(2,c);g>d&&(c=-1+c|0,g/=2);g=d/g*b;d=+l.Math.floor(g);g-=d;d=.5>g?d:.5<g?1+d:0!==d%2?
1+d:d;2<=d/b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+l.Math.pow(2,-1074),c=+l.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new P).C(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.n^a.Q}pb.prototype.$classData=w({ad:0},"scala.scalajs.runtime.Bits$",{ad:1,c:1});var qb=void 0;function za(){qb||(qb=(new pb).b());return qb}function rb(){}rb.prototype=new y;rb.prototype.constructor=rb;rb.prototype.b=function(){return this};
function wa(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}rb.prototype.$classData=w({cd:0},"scala.scalajs.runtime.RuntimeString$",{cd:1,c:1});var sb=void 0;function xa(){sb||(sb=(new rb).b());return sb}function tb(){}tb.prototype=new y;tb.prototype.constructor=tb;tb.prototype.b=function(){return this};function ub(a,b){return b&&b.$classData&&b.$classData.u.Sa?b.O:b}
function vb(a,b){return b&&b.$classData&&b.$classData.u.F?b:(new wb).va(b)}tb.prototype.$classData=w({dd:0},"scala.scalajs.runtime.package$",{dd:1,c:1});var xb=void 0;function yb(){xb||(xb=(new tb).b());return xb}function zb(){}zb.prototype=new y;zb.prototype.constructor=zb;zb.prototype.b=function(){return this};zb.prototype.$classData=w({hd:0},"scala.runtime.ScalaRunTime$",{hd:1,c:1});var Ab=void 0;function Bb(){}Bb.prototype=new y;Bb.prototype.constructor=Bb;f=Bb.prototype;f.b=function(){return this};
f.Ka=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};function Cb(a,b){a=2147483647<b?2147483647:-2147483648>b?-2147483648:b|0;if(a===b)return a;a=x();var c;if(-9223372036854775808>b)a.za=-2147483648,c=0;else if(0x7fffffffffffffff<=b)a.za=2147483647,c=-1;else{c=b|0;var d=b/4294967296|0;a.za=0>b&&0!==c?-1+d|0:d}a=a.za;x();return(0>a?-(4294967296*+((0!==c?~a:-a|0)>>>0)+ +((-c|0)>>>0)):4294967296*a+ +(c>>>0))===b?c^a:ya(za(),b)}
function fb(a,b){return null===b?0:"number"===typeof b?Cb(0,+b):ta(b)?(a=null===b?x().la:b,b=(new P).C(a.n,a.Q),a=b.n,b=b.Q,b===a>>31?a:a^b):va(b)}f.T=function(a,b){a=this.Ka(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};f.fa=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};f.$classData=w({jd:0},"scala.runtime.Statics$",{jd:1,c:1});var Db=void 0;function M(){Db||(Db=(new Bb).b());return Db}function Eb(){}Eb.prototype=new y;
Eb.prototype.constructor=Eb;function Fb(){}Fb.prototype=Eb.prototype;function Q(){this.t=null}Q.prototype=new y;Q.prototype.constructor=Q;function Gb(){}Gb.prototype=Q.prototype;Q.prototype.tb=function(){if(void 0===l.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=vb(yb(),b),null!==a)if(a&&a.$classData&&a.$classData.u.Sa)a=a.O;else throw ub(yb(),a);else throw b;}this.stackdata=a}else l.Error.captureStackTrace(this),this.stackdata=this;return this};Q.prototype.Ia=function(){return this.t};
Q.prototype.r=function(){var a=D(ia(this)),b=this.Ia();return null===b?a:a+": "+b};Q.prototype.E=function(a){this.t=a;this.tb();return this};function Ib(){this.Ra=0}Ib.prototype=new cb;Ib.prototype.constructor=Ib;Ib.prototype.b=function(){Jb=this;this.Ra=wa(xa(),"Seq");wa(xa(),"Map");wa(xa(),"Set");return this};function Kb(a){var b=Lb();if(a&&a.$classData&&a.$classData.u.Dd){for(var c=0,d=b.Ra,g=a;!g.md();)a=g.ld(),g=g.Qd(),d=b.T(d,fb(M(),a)),c=1+c|0;b=b.fa(d,c)}else b=db(b,a,b.Ra);return b}
Ib.prototype.$classData=w({mc:0},"scala.util.hashing.MurmurHash3$",{mc:1,xd:1,c:1});var Jb=void 0;function Lb(){Jb||(Jb=(new Ib).b());return Jb}function R(){}R.prototype=new ob;R.prototype.constructor=R;function Mb(){}Mb.prototype=R.prototype;R.prototype.b=function(){(new Nb).wa(this);return this};function S(){}S.prototype=new y;S.prototype.constructor=S;function Ob(){}Ob.prototype=S.prototype;S.prototype.wa=function(a){if(null===a)throw ub(yb(),null);return this};function Pb(){}Pb.prototype=new y;
Pb.prototype.constructor=Pb;function Qb(){}Qb.prototype=Pb.prototype;Pb.prototype.r=function(){return"\x3cfunction1\x3e"};function Rb(){this.p=!1}Rb.prototype=new y;Rb.prototype.constructor=Rb;Rb.prototype.r=function(){return""+this.p};function kb(){var a=new Rb;a.p=!0;return a}Rb.prototype.$classData=w({ed:0},"scala.runtime.BooleanRef",{ed:1,c:1,f:1});var sa=w({fd:0},"scala.runtime.BoxedUnit",{fd:1,c:1,f:1},void 0,void 0,function(a){return void 0===a});function K(){this.p=0}K.prototype=new y;
K.prototype.constructor=K;K.prototype.r=function(){return""+this.p};K.prototype.ga=function(a){this.p=a;return this};K.prototype.$classData=w({gd:0},"scala.runtime.IntRef",{gd:1,c:1,f:1});var ra=w({Sb:0},"java.lang.Boolean",{Sb:1,c:1,f:1,x:1},void 0,void 0,function(a){return"boolean"===typeof a});function T(){this.G=0}T.prototype=new y;T.prototype.constructor=T;T.prototype.r=function(){return l.String.fromCharCode(this.G)};function Sb(a){var b=new T;b.G=a;return b}T.prototype.B=function(){return this.G};
T.prototype.$classData=w({Ub:0},"java.lang.Character",{Ub:1,c:1,f:1,x:1});function Tb(){this.t=null}Tb.prototype=new Gb;Tb.prototype.constructor=Tb;function Ub(){}Ub.prototype=Tb.prototype;function Vb(){}Vb.prototype=new Ob;Vb.prototype.constructor=Vb;Vb.prototype.b=function(){S.prototype.wa.call(this,Ta());return this};Vb.prototype.$classData=w({yc:0},"scala.collection.IndexedSeq$$anon$1",{yc:1,Oc:1,c:1,Kc:1});function Wb(){}Wb.prototype=new Mb;Wb.prototype.constructor=Wb;function Xb(){}
Xb.prototype=Wb.prototype;function Nb(){this.ka=null}Nb.prototype=new Ob;Nb.prototype.constructor=Nb;Nb.prototype.wa=function(a){if(null===a)throw ub(yb(),null);this.ka=a;S.prototype.wa.call(this,a);return this};Nb.prototype.$classData=w({Nc:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{Nc:1,Oc:1,c:1,Kc:1});function Yb(){this.sb=null}Yb.prototype=new Qb;Yb.prototype.constructor=Yb;Yb.prototype.W=function(a){return(0,this.sb)(a)};function eb(a){var b=new Yb;b.sb=a;return b}
Yb.prototype.$classData=w({$c:0},"scala.scalajs.runtime.AnonFunction1",{$c:1,Pd:1,c:1,Ua:1});function Zb(){this.za=0;this.la=null}Zb.prototype=new y;Zb.prototype.constructor=Zb;Zb.prototype.b=function(){$b=this;this.la=(new P).C(0,0);return this};
function ac(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,k=a,e=b;for(a=b=0;0<=c&&0!==(-2097152&e);){var t=k,m=e,L=g,Hb=d;if(m===Hb?(-2147483648^t)>=(-2147483648^L):(-2147483648^m)>=(-2147483648^Hb))t=e,m=d,e=k-g|0,t=(-2147483648^e)>(-2147483648^k)?-1+(t-m|0)|0:t-m|0,k=e,e=t,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;t=d>>>1|0;g=g>>>1|0|d<<31;d=t}c=e;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*e+ +(k>>>0),k=c/1E9,g=k/4294967296|0,d=b,b=k=d+(k|0)|0,a=(-2147483648^k)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,k=c%1E9|0;c=""+k;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}Zb.prototype.$classData=w({bd:0},"scala.scalajs.runtime.RuntimeLong$",{bd:1,c:1,M:1,f:1});var $b=void 0;function x(){$b||($b=(new Zb).b());return $b}
var ja=w({Pb:0},"java.lang.String",{Pb:1,c:1,f:1,xb:1,x:1},void 0,void 0,function(a){return"string"===typeof a}),la=w({Tb:0},"java.lang.Byte",{Tb:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return ka(a)}),qa=w({Xb:0},"java.lang.Double",{Xb:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return"number"===typeof a}),pa=w({Yb:0},"java.lang.Float",{Yb:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return"number"===typeof a}),oa=w({ac:0},"java.lang.Integer",{ac:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),ua=w({bc:0},"java.lang.Long",{bc:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return ta(a)});function bc(){this.t=null}bc.prototype=new Ub;bc.prototype.constructor=bc;function U(){}U.prototype=bc.prototype;var na=w({ec:0},"java.lang.Short",{ec:1,S:1,c:1,f:1,x:1},void 0,void 0,function(a){return ma(a)});function cc(){this.q=null}cc.prototype=new y;cc.prototype.constructor=cc;f=cc.prototype;f.b=function(){this.q="";return this};f.r=function(){return this.q};
f.ga=function(a){cc.prototype.b.call(this);if(0>a)throw(new dc).b();return this};f.J=function(){return this.q.length|0};f.$classData=w({fc:0},"java.lang.StringBuilder",{fc:1,c:1,xb:1,nd:1,f:1});function V(){}V.prototype=new y;V.prototype.constructor=V;function ec(){}ec.prototype=V.prototype;V.prototype.r=function(){return(this.P()?"non-empty":"empty")+" iterator"};V.prototype.ua=function(a){for(;this.P();)a.W(this.L())};V.prototype.Xa=function(a,b,c,d){return jb(this,a,b,c,d)};
function P(){this.Q=this.n=0}P.prototype=new Fb;P.prototype.constructor=P;f=P.prototype;f.Ja=function(a,b,c){P.prototype.C.call(this,a|b<<22,b>>10|c<<12);return this};f.r=function(){x();var a=this.n,b=this.Q;return b===a>>31?""+a:0>b?"-"+ac(-a|0,0!==a?~b:-b|0):ac(a,b)};f.C=function(a,b){this.n=a;this.Q=b;return this};f.ga=function(a){P.prototype.C.call(this,a,a>>31);return this};f.B=function(){return this.n^this.Q};function ta(a){return!!(a&&a.$classData&&a.$classData.u.Kb)}
f.$classData=w({Kb:0},"scala.scalajs.runtime.RuntimeLong",{Kb:1,S:1,c:1,f:1,x:1});function Wa(){this.ra=this.G=0}Wa.prototype=new y;Wa.prototype.constructor=Wa;f=Wa.prototype;f.Na=function(){return"Diff"};f.La=function(){return 2};f.Ma=function(a){switch(a){case 0:return this.G;case 1:return this.ra;default:throw(new W).D(""+a);}};f.r=function(){Ab||(Ab=(new zb).b());var a=this.Bb();return ib(a,this.Na()+"(",",")};
f.B=function(){var a=-889275714,a=M().T(a,Cb(M(),this.G)),a=M().T(a,Cb(M(),this.ra));return M().fa(a,2)};f.Bb=function(){return fc(this)};f.$classData=w({Nb:0},"Analyzer$Diff",{Nb:1,c:1,kc:1,Oa:1,M:1,f:1});function F(){this.t=null}F.prototype=new U;F.prototype.constructor=F;F.prototype.b=function(){Q.prototype.E.call(this,null);return this};F.prototype.$classData=w({Zb:0},"java.lang.IllegalArgumentException",{Zb:1,I:1,H:1,F:1,c:1,f:1});function W(){this.t=null}W.prototype=new U;
W.prototype.constructor=W;W.prototype.D=function(a){Q.prototype.E.call(this,a);return this};W.prototype.$classData=w({$b:0},"java.lang.IndexOutOfBoundsException",{$b:1,I:1,H:1,F:1,c:1,f:1});function dc(){this.t=null}dc.prototype=new U;dc.prototype.constructor=dc;dc.prototype.b=function(){Q.prototype.E.call(this,null);return this};dc.prototype.$classData=w({cc:0},"java.lang.NegativeArraySizeException",{cc:1,I:1,H:1,F:1,c:1,f:1});function gc(){this.t=null}gc.prototype=new U;
gc.prototype.constructor=gc;gc.prototype.b=function(){Q.prototype.E.call(this,null);return this};gc.prototype.$classData=w({dc:0},"java.lang.NullPointerException",{dc:1,I:1,H:1,F:1,c:1,f:1});function $a(){this.t=null}$a.prototype=new U;$a.prototype.constructor=$a;$a.prototype.D=function(a){Q.prototype.E.call(this,a);return this};$a.prototype.$classData=w({gc:0},"java.lang.UnsupportedOperationException",{gc:1,I:1,H:1,F:1,c:1,f:1});function X(){this.t=null}X.prototype=new U;
X.prototype.constructor=X;X.prototype.D=function(a){Q.prototype.E.call(this,a);return this};X.prototype.$classData=w({hc:0},"java.util.NoSuchElementException",{hc:1,I:1,H:1,F:1,c:1,f:1});function G(){this.ha=this.Ab=this.t=null;this.Ba=!1}G.prototype=new U;G.prototype.constructor=G;
G.prototype.Ia=function(){if(!this.Ba&&!this.Ba){var a;if(null===this.ha)a="null";else try{a=ha(this.ha)+" ("+("of class "+D(ia(this.ha)))+")"}catch(b){if(null!==vb(yb(),b))a="an instance of class "+D(ia(this.ha));else throw b;}this.Ab=a;this.Ba=!0}return this.Ab};G.prototype.va=function(a){this.ha=a;Q.prototype.E.call(this,null);return this};G.prototype.$classData=w({ic:0},"scala.MatchError",{ic:1,I:1,H:1,F:1,c:1,f:1});function N(){}N.prototype=new ec;N.prototype.constructor=N;N.prototype.b=function(){return this};
N.prototype.L=function(){throw(new X).D("next on empty iterator");};N.prototype.P=function(){return!1};N.prototype.$classData=w({Ec:0},"scala.collection.Iterator$$anon$2",{Ec:1,Pa:1,c:1,Qa:1,ja:1,ia:1});function Y(){this.Za=this.aa=0;this.Lb=null}Y.prototype=new ec;Y.prototype.constructor=Y;Y.prototype.L=function(){var a=this.Lb.Ma(this.aa);this.aa=1+this.aa|0;return a};function fc(a){var b=new Y;b.Lb=a;b.aa=0;b.Za=a.La();return b}Y.prototype.P=function(){return this.aa<this.Za};
Y.prototype.$classData=w({id:0},"scala.runtime.ScalaRunTime$$anon$1",{id:1,Pa:1,c:1,Qa:1,ja:1,ia:1});function hc(){}hc.prototype=new Xb;hc.prototype.constructor=hc;function ic(){}ic.prototype=hc.prototype;function Va(){this.ca=this.K=this.$=0;this.ob=this.lb=this.ib=this.fb=this.cb=this.da=null}Va.prototype=new y;Va.prototype.constructor=Va;f=Va.prototype;f.g=function(){return this.ib};f.b=function(){this.da=q(B(z),[32]);this.ca=1;this.K=this.$=0;return this};f.o=function(){return this.ca};
f.ea=function(a){this.ob=a};f.j=function(){return this.da};f.k=function(a){this.fb=a};f.l=function(){return this.lb};f.h=function(a){this.cb=a};f.v=function(a){this.lb=a};f.d=function(){return this.cb};f.w=function(){return this.ob};f.A=function(a){this.ca=a};f.e=function(){return this.fb};f.i=function(a){this.da=a};f.m=function(a){this.ib=a};f.$classData=w({Vc:0},"scala.collection.immutable.VectorBuilder",{Vc:1,c:1,Yc:1,Xc:1,Qc:1,Lc:1,Jb:1});
function jc(){this.Ha=this.n=this.z=this.Ga=0;this.V=!1;this.Ca=0;this.pb=this.mb=this.jb=this.gb=this.db=this.Ea=null}jc.prototype=new ec;jc.prototype.constructor=jc;f=jc.prototype;
f.L=function(){if(!this.V)throw(new X).D("reached iterator end");var a=this.Ea.a[this.n];this.n=1+this.n|0;if(this.n===this.Ha)if((this.z+this.n|0)<this.Ga){var b=32+this.z|0,c=this.z^b;if(1024>c)this.i(this.d().a[31&(b>>>5|0)]);else if(32768>c)this.h(this.e().a[31&(b>>>10|0)]),this.i(this.d().a[0]);else if(1048576>c)this.k(this.g().a[31&(b>>>15|0)]),this.h(this.e().a[0]),this.i(this.d().a[0]);else if(33554432>c)this.m(this.l().a[31&(b>>>20|0)]),this.k(this.g().a[0]),this.h(this.e().a[0]),this.i(this.d().a[0]);
else if(1073741824>c)this.v(this.w().a[31&(b>>>25|0)]),this.m(this.l().a[0]),this.k(this.g().a[0]),this.h(this.e().a[0]),this.i(this.d().a[0]);else throw(new F).b();this.z=b;b=this.Ga-this.z|0;this.Ha=32>b?b:32;this.n=0}else this.V=!1;return a};f.g=function(){return this.jb};f.o=function(){return this.Ca};f.ea=function(a){this.pb=a};f.C=function(a,b){this.Ga=b;this.z=-32&a;this.n=31&a;a=b-this.z|0;this.Ha=32>a?a:32;this.V=(this.z+this.n|0)<b;return this};f.j=function(){return this.Ea};
f.k=function(a){this.gb=a};f.l=function(){return this.mb};f.h=function(a){this.db=a};f.P=function(){return this.V};f.v=function(a){this.mb=a};f.d=function(){return this.db};f.w=function(){return this.pb};f.A=function(a){this.Ca=a};f.e=function(){return this.gb};f.i=function(a){this.Ea=a};f.m=function(a){this.jb=a};f.$classData=w({Wc:0},"scala.collection.immutable.VectorIterator",{Wc:1,Pa:1,c:1,Qa:1,ja:1,ia:1,Jb:1});function kc(){}kc.prototype=new ic;kc.prototype.constructor=kc;function lc(){}
lc.prototype=kc.prototype;function Za(){}Za.prototype=new y;Za.prototype.constructor=Za;Za.prototype.b=function(){return this};Za.prototype.$classData=w({lc:0},"scala.math.Ordering$Double$",{lc:1,c:1,vd:1,ud:1,od:1,wd:1,sd:1,M:1,f:1});var Ya=void 0;function mc(){}mc.prototype=new lc;mc.prototype.constructor=mc;mc.prototype.b=function(){R.prototype.b.call(this);nc=this;(new Vb).b();return this};
mc.prototype.$classData=w({xc:0},"scala.collection.IndexedSeq$",{xc:1,Gb:1,Hb:1,Cb:1,Db:1,Eb:1,c:1,Ib:1,Fb:1});var nc=void 0;function Ta(){nc||(nc=(new mc).b());return nc}function Z(){this.R=this.Fa=0;this.ka=null}Z.prototype=new ec;Z.prototype.constructor=Z;Z.prototype.L=function(){this.R>=this.Fa&&(hb||(hb=(new gb).b()),hb.rb.L());var a=this.ka.oa(this.R);this.R=1+this.R|0;return a};Z.prototype.P=function(){return this.R<this.Fa};
Z.prototype.$classData=w({Ac:0},"scala.collection.IndexedSeqLike$Elements",{Ac:1,Pa:1,c:1,Qa:1,ja:1,ia:1,yd:1,M:1,f:1});function I(){}I.prototype=new lc;I.prototype.constructor=I;I.prototype.b=function(){R.prototype.b.call(this);return this};I.prototype.$classData=w({Sc:0},"scala.collection.immutable.IndexedSeq$",{Sc:1,Gb:1,Hb:1,Cb:1,Db:1,Eb:1,c:1,Ib:1,Fb:1});var Sa=void 0;function wb(){this.O=this.t=null}wb.prototype=new U;wb.prototype.constructor=wb;f=wb.prototype;f.Na=function(){return"JavaScriptException"};
f.La=function(){return 1};f.tb=function(){this.stackdata=this.O;return this};f.Ma=function(a){switch(a){case 0:return this.O;default:throw(new W).D(""+a);}};f.Ia=function(){return ha(this.O)};f.va=function(a){this.O=a;Q.prototype.E.call(this,null);return this};f.B=function(){var a;a=Lb();var b=this.La();if(0===b)a=this.Na(),a=wa(xa(),a);else{for(var c=-889275714,d=0;d<b;)c=a.T(c,fb(M(),this.Ma(d))),d=1+d|0;a=a.fa(c,b)}return a};f.Bb=function(){return fc(this)};
f.$classData=w({Sa:0},"scala.scalajs.js.JavaScriptException",{Sa:1,I:1,H:1,F:1,c:1,f:1,kc:1,Oa:1,M:1});function oc(){this.Va=null}oc.prototype=new lc;oc.prototype.constructor=oc;oc.prototype.b=function(){R.prototype.b.call(this);pc=this;this.Va=(new Xa).Ja(0,0,0);return this};oc.prototype.$classData=w({Uc:0},"scala.collection.immutable.Vector$",{Uc:1,Gb:1,Hb:1,Cb:1,Db:1,Eb:1,c:1,Ib:1,Fb:1,M:1,f:1});var pc=void 0;function Ua(){pc||(pc=(new oc).b());return pc}function qc(){}qc.prototype=new y;
qc.prototype.constructor=qc;function rc(){}rc.prototype=qc.prototype;qc.prototype.Xa=function(a,b,c,d){return jb(this,a,b,c,d)};function sc(){}sc.prototype=new rc;sc.prototype.constructor=sc;function tc(){}tc.prototype=sc.prototype;sc.prototype.ua=function(a){for(var b=this.wb();b.P();)a.W(b.L())};function uc(){}uc.prototype=new tc;uc.prototype.constructor=uc;function vc(){}vc.prototype=uc.prototype;
uc.prototype.r=function(){var a;a:{a=D(ia(this));for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))a="";else for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var g=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var k=1+b|0;if(b===g&&d!==(a.length|0)){a=c;break a}for(;;)if(-1!==
b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var g=-1===b?!0:46===(65535&(a.charCodeAt(b)|0)),e;(e=g)||(e=65535&(a.charCodeAt(k)|0),e=!(90<e&&127>e||65>e));if(e){d=a.substring(k,d);k=c;if(null===k)throw(new gc).b();c=""===k?d:""+d+Sb(46)+c;if(g){a=c;break a}}}}return ib(this,a+"(",", ")};function wc(){}wc.prototype=new vc;wc.prototype.constructor=wc;function xc(){}xc.prototype=wc.prototype;
function Xa(){this.ta=this.sa=this.U=0;this.ab=!1;this.Da=0;this.qb=this.nb=this.kb=this.hb=this.eb=this.bb=null}Xa.prototype=new vc;Xa.prototype.constructor=Xa;f=Xa.prototype;f.g=function(){return this.kb};f.oa=function(a){var b=a+this.U|0;if(0<=a&&b<this.sa)a=b;else throw(new W).D(""+a);return Na(this,a,a^this.ta)};f.yb=function(a){return this.J()-a|0};f.o=function(){return this.Da};f.W=function(a){return this.oa(a|0)};f.Ja=function(a,b,c){this.U=a;this.sa=b;this.ta=c;this.ab=!1;return this};
f.ea=function(a){this.qb=a};f.j=function(){return this.bb};f.k=function(a){this.hb=a};f.l=function(){return this.nb};f.wb=function(){return ab(this)};f.h=function(a){this.eb=a};f.J=function(){return this.sa-this.U|0};f.v=function(a){this.nb=a};f.d=function(){return this.eb};f.w=function(){return this.qb};
function ab(a){var b=(new jc).C(a.U,a.sa);Pa(b,a,a.Da);if(a.ab){var c=a.ta,d=-1+b.o()|0;switch(d){case 5:b.ea(E(b.w()));b.v(E(b.l()));b.m(E(b.g()));b.k(E(b.e()));b.h(E(b.d()));b.w().a[31&(c>>>25|0)]=b.l();b.l().a[31&(c>>>20|0)]=b.g();b.g().a[31&(c>>>15|0)]=b.e();b.e().a[31&(c>>>10|0)]=b.d();b.d().a[31&(c>>>5|0)]=b.j();break;case 4:b.v(E(b.l()));b.m(E(b.g()));b.k(E(b.e()));b.h(E(b.d()));b.l().a[31&(c>>>20|0)]=b.g();b.g().a[31&(c>>>15|0)]=b.e();b.e().a[31&(c>>>10|0)]=b.d();b.d().a[31&(c>>>5|0)]=b.j();
break;case 3:b.m(E(b.g()));b.k(E(b.e()));b.h(E(b.d()));b.g().a[31&(c>>>15|0)]=b.e();b.e().a[31&(c>>>10|0)]=b.d();b.d().a[31&(c>>>5|0)]=b.j();break;case 2:b.k(E(b.e()));b.h(E(b.d()));b.e().a[31&(c>>>10|0)]=b.d();b.d().a[31&(c>>>5|0)]=b.j();break;case 1:b.h(E(b.d()));b.d().a[31&(c>>>5|0)]=b.j();break;case 0:break;default:throw(new G).va(d);}}1<b.Ca&&Oa(b,a.U,a.U^a.ta);return b}f.B=function(){return Kb(this)};f.A=function(a){this.Da=a};f.e=function(){return this.hb};f.i=function(a){this.bb=a};
f.m=function(a){this.kb=a};f.$classData=w({Tc:0},"scala.collection.immutable.Vector",{Tc:1,oc:1,nc:1,pc:1,c:1,Ic:1,Jc:1,Rc:1,Mc:1,ja:1,ia:1,vc:1,Fc:1,uc:1,Pc:1,Bc:1,qc:1,rc:1,Cc:1,Oa:1,Gc:1,jc:1,Ua:1,sc:1,tc:1,Hc:1,Bd:1,Ed:1,Cd:1,Gd:1,qd:1,wc:1,zc:1,Jb:1,M:1,f:1,zd:1});function O(){this.y=null}O.prototype=new xc;O.prototype.constructor=O;f=O.prototype;f.b=function(){O.prototype.Qb.call(this,16,"");return this};f.oa=function(a){a=65535&(this.y.q.charCodeAt(a)|0);return Sb(a)};
f.yb=function(a){return this.J()-a|0};f.W=function(a){a=65535&(this.y.q.charCodeAt(a|0)|0);return Sb(a)};f.r=function(){return this.y.q};f.ua=function(a){for(var b=0,c=this.J();b<c;)a.W(this.oa(b)),b=1+b|0};function lb(a,b){a=a.y;a.q=""+a.q+b}f.wb=function(){var a=new Z;a.Fa=this.y.J();if(null===this)throw ub(yb(),null);a.ka=this;a.R=0;return a};f.Qb=function(a,b){a=(new cc).ga((b.length|0)+a|0);a.q=""+a.q+b;O.prototype.Rb.call(this,a);return this};f.J=function(){return this.y.J()};
f.Rb=function(a){this.y=a;return this};function mb(a,b){var c=a.y;c.q+=""+b;return a}f.B=function(){return Kb(this)};f.$classData=w({Zc:0},"scala.collection.mutable.StringBuilder",{Zc:1,Hd:1,oc:1,nc:1,pc:1,c:1,Ic:1,Jc:1,Rc:1,Mc:1,ja:1,ia:1,vc:1,Fc:1,uc:1,Pc:1,Bc:1,qc:1,rc:1,Cc:1,Oa:1,Gc:1,jc:1,Ua:1,sc:1,tc:1,Hc:1,Md:1,Ld:1,Od:1,rd:1,Nd:1,Id:1,pd:1,Wb:1,xb:1,Jd:1,wc:1,zc:1,Kd:1,Fd:1,Ad:1,td:1,x:1,Yc:1,Xc:1,Qc:1,Lc:1,M:1,f:1});bb||(bb=(new H).b());aa.Analyzer=bb;
}).call(this);
//# sourceMappingURL=analyze-opt.js.map
